
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udzwdyefhgbowjpjbhea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkendkeWVmaGdib3dqcGpiaGVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3ODUxNzUsImV4cCI6MjA1NzM2MTE3NX0.b_3V1tMbu0L93JxYDDASrdKqLKgfYoC3J25eZKG83yk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
